name: segodnya_ya_pozvolyu_sebe_kofe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cygre
      fonts:
        - asset: assets/fonts/Cygre-Thin.ttf
          weight: 100
        - asset: assets/fonts/Cygre-Light.ttf
          weight: 300
        - asset: assets/fonts/Cygre-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cygre-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cygre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cygre-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cygre-Black.ttf
          weight: 900
    - family: CygreItalic
      fonts:
        - asset: assets/fonts/Cygre-ThinIt.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Cygre-LightIt.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Cygre-RegularIt.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Cygre-MediumIt.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Cygre-SemiBoldIt.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Cygre-BoldIt.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Cygre-BlackIt.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  linux: true
  macos:
    generate: true
    image_path: "assets/images/icon.PNG"
  windows:
    generate: true
    image_path: "assets/images/icon.PNG"
    icon_size: 48 # Можно изменить размер при необходимости
  web:
    generate: true
    image_path: "assets/images/icon.PNG"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: "assets/images/icon.PNG"
